In [ ]:
#EXPLORACION DE DATOS DE YELP

In [ ]:
#Filtrado de datos de Business.csv para encontrar los locales que se encuentran en la base de datos de Yelp para obtener el n√∫mero de locales

In [2]:
import pandas as pd
from IPython.display import display  # Importa la funci√≥n display

# Ruta del archivo "Business.csv"
ruta_del_archivo_csv = "C:/Users/Fede/Documents/Henry/Proyecto 3/Business.csv"

# Cargar el archivo "Business.csv" en un DataFrame
data = pd.read_csv(ruta_del_archivo_csv)

# Nombres a filtrar
nombres_a_filtrar = ['KFC', "Domino's Pizza", 'McDonald\'s', 'Subway', 'Pizza Hut']

nombres_a_filtrar = [nombre.lower() for nombre in nombres_a_filtrar]

# Filtrar las filas que contienen los nombres especificados (insensible a may√∫sculas y min√∫sculas)
filas_filtradas = data[data['name'].str.lower().isin(nombres_a_filtrar)]

# Mostrar el DataFrame filtrado con display
display(filas_filtradas)

# Calcular el promedio de estrellas para cada nombre filtrado
promedio_estrellas = filas_filtradas.groupby('name')['stars'].mean()

# Mostrar el DataFrame con los promedios utilizando display
display(promedio_estrellas.reset_index())

C:\Users\Fede\AppData\Local\Temp\ipykernel_15208\3259117736.py:8: DtypeWarning: Columns (14,15,16,17,18,19,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(ruta_del_archivo_csv)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,state.1,postal_code.1,latitude.1,longitude.1,stars.1,review_count.1,is_open.1,attributes.1,categories.1,hours.1
29,sqSqqLy0sN8n2IZrAbzidQ,Domino's Pizza,3001 Highway 31 W,White House,CA,37188,36.464747,-86.659187,3.5,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,VZzivJEbmHItOxNXJB3SpA,Subway,"330 Franklin Rd, Ste 900-d",Brentwood,TN,37027,36.026363,-86.789473,2.5,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,LGqiubTmpJ-A1L5n7dmc6g,Domino's Pizza,"1525 Lapalco Blvd, # A",Harvey,FL,70058,29.875320,-90.045817,1.5,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,yM8LlTInbQH4FwWC97lz6w,McDonald's,1919 S Jefferson,St. Louis,PA,63104,38.612495,-90.221942,1.5,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,bDAlJYMIzwOewIThe2IZjQ,Domino's Pizza,4430 South Mann,Indianapolis,PA,46221,39.699929,-86.241631,4.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150056,zgBo9QTMbb2PrlIYgXjOXA,Domino's Pizza,"651 Terry Parkway, Ste 101",Gretna,MO,70056,29.908808,-90.029140,2.0,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150110,eQ83iTisgPFzJ1YBO3p-IA,Domino's Pizza,4000 W Main St,Belleville,LA,62226,38.536365,-90.019293,2.0,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150147,V-snSOHDO_mrWOBtJHtg4w,Domino's Pizza,3041 Dickerson Pike,Nashville,LA,37207,36.228015,-86.758557,2.0,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150231,C96ynw3G1KrqBOdafxbTKw,Subway,4882 Sun City Center Blvd,Sun City Center,FL,33573,27.714605,-82.335851,4.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150313,sf_oQ62L8UEnOOLf00nNGA,Pizza Hut,5028 Old Hickory,Hermitage,MO,37076,36.193201,-86.614748,3.0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

             name     stars
0  Domino's Pizza  2.281356
1             KFC  1.859649
2      McDonald's  1.863442
3       Pizza Hut  2.033088
4          Subway  2.586057

In [ ]:
#Filtrado de datos de Business.csv para encontrar los locales que se encuentran en la base de datos de Yelp para obtener el promedio de estrellas

In [3]:
import pandas as pd
from IPython.display import display  # Importa la funci√≥n display

# Ruta del archivo "Business.csv"
ruta_del_archivo_csv = "C:/Users/Fede/Documents/Henry/Proyecto 3/Business.csv"

# Cargar el archivo "Business.csv" en un DataFrame
data = pd.read_csv(ruta_del_archivo_csv)

# Nombres a filtrar
nombres_a_filtrar = ['KFC', "Domino's Pizza", 'McDonald\'s', 'Subway', 'Pizza Hut']

# Convertir los nombres a min√∫sculas para que la comparaci√≥n sea insensible a may√∫sculas y min√∫sculas
nombres_a_filtrar = [nombre.lower() for nombre in nombres_a_filtrar]

# Filtrar las filas que contienen los nombres especificados (insensible a may√∫sculas y min√∫sculas)
filas_filtradas = data[data['name'].str.lower().isin(nombres_a_filtrar)]

# Realizar el conteo de cada nombre
conteo_nombres = filas_filtradas['name'].value_counts()

# Mostrar el conteo de nombres con display
display(conteo_nombres)

# Guardar el DataFrame en un archivo CSV llamado "business.csv"
data.to_csv("business.csv", index=False)

C:\Users\Fede\AppData\Local\Temp\ipykernel_15208\3762686566.py:8: DtypeWarning: Columns (14,15,16,17,18,19,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(ruta_del_archivo_csv)

McDonald's        703
Subway            459
Domino's Pizza    295
Pizza Hut         272
KFC               171
Name: name, dtype: int64