In [ ]:
#ETL YELP

In [1]:
import pandas as pd

# Ruta al archivo pickle
archivo_pickle = "C:/Users/Fede/Documents/Henry/Proyecto 3/Yelp/business.pkl"

# Cargar el archivo pickle
df = pd.read_pickle(archivo_pickle)

# Guardar el DataFrame en un archivo CSV llamado "Business.csv"
df.to_csv("Business.csv", index=False)

# Mostrar los tipos de datos (dtype) de las columnas
print(df.dtypes)

business_id     object
name            object
address         object
city            object
state           object
postal_code     object
latitude        object
longitude       object
stars           object
review_count    object
is_open         object
attributes      object
categories      object
hours           object
business_id     object
name            object
address         object
city            object
state           object
postal_code     object
latitude        object
longitude       object
stars           object
review_count    object
is_open         object
attributes      object
categories      object
hours           object
dtype: object

In [2]:
import pandas as pd

# Ruta al archivo CSV
archivo_csv = r'C:\Users\Fede\Documents\Henry\Proyecto 3\etl\Business.csv'

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv(archivo_csv)

# Calcular el porcentaje de nulos en cada columna
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100

# Mostrar el resultado
print(porcentaje_nulos)

C:\Users\Fede\AppData\Local\Temp\ipykernel_3220\3554362029.py:7: DtypeWarning: Columns (14,15,16,17,18,19,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(archivo_csv)

business_id        0.000000
name               0.000000
address            3.410134
city               0.000000
state              0.001995
postal_code        0.048555
latitude           0.000000
longitude          0.000000
stars              0.000000
review_count       0.000000
is_open            0.000000
attributes         9.141580
categories         0.068509
hours             15.446370
business_id.1     99.996674
name.1            99.996674
address.1         99.996674
city.1            99.996674
state.1           99.996674
postal_code.1     99.996674
latitude.1        99.996674
longitude.1       99.996674
stars.1           99.996674
review_count.1    99.996674
is_open.1         99.996674
attributes.1      99.996674
categories.1      99.996674
hours.1           99.996674
dtype: float64

In [4]:
import pandas as pd

# Ruta al archivo CSV original
archivo_csv = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Business.csv'

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv(archivo_csv)

# Lista de columnas a eliminar
columnas_a_eliminar = [
    'business_id.1', 'name.1', 'address.1', 'city.1', 'state.1',
    'postal_code.1', 'latitude.1', 'longitude.1', 'stars.1',
    'review_count.1', 'is_open.1', 'attributes.1', 'categories.1', 'hours.1'
]

# Eliminar las columnas
df = df.drop(columns=columnas_a_eliminar)

# Guardar el DataFrame resultante en un nuevo archivo CSV
df.to_csv('Business2.csv', index=False)

# Mostrar el DataFrame resultante con display
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
display(df)

C:\Users\Fede\AppData\Local\Temp\ipykernel_3220\1806303950.py:7: DtypeWarning: Columns (14,15,16,17,18,19,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(archivo_csv)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,NaN,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,NaN,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,NaN,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,IN,T6J 5H2,53.468419,-113.492054,3.0,13,1,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,DE,37204,36.115118,-86.766925,4.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,AB,46250,39.908707,-86.065088,3.5,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",NaN
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,AB,62025,38.782351,-89.950558,4.0,24,1,"{'BusinessParking': ""{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,TN,33572,27.771002,-82.394910,4.5,9,1,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [5]:
import pandas as pd

# Ruta al archivo CSV
archivo_csv = "C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Business2.csv"

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv(archivo_csv)

# Calcular el porcentaje de nulos en cada columna
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100

# Mostrar el resultado
print(porcentaje_nulos)

business_id      0.000000
name             0.000000
address          3.410134
city             0.000000
state            0.001995
postal_code      0.048555
latitude         0.000000
longitude        0.000000
stars            0.000000
review_count     0.000000
is_open          0.000000
attributes       9.141580
categories       0.068509
hours           15.446370
dtype: float64

In [6]:
import pandas as pd

# Ruta al archivo CSV original
archivo_csv = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Business2.csv'

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv(archivo_csv)

# Transformar las columnas según las especificaciones
df['stars'] = df['stars'].astype(float)
df['review_count'] = df['review_count'].astype(int)
df.drop(columns=['postal_code', 'latitude', 'longitude', 'is_open'], inplace=True)

# Guardar el DataFrame resultante en un nuevo archivo CSV
df.to_csv('Business3.csv', index=False)

# Mostrar el DataFrame resultante con display
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
display(df)

,business_id,name,address,city,state,stars,review_count,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,NaN,5.0,7,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,NaN,3.0,15,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,NaN,3.5,22,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,4.0,80,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,4.5,13,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,IN,3.0,13,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,DE,4.0,5,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,AB,3.5,8,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",NaN
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,AB,4.0,24,"{'BusinessParking': ""{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,TN,4.5,9,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [7]:
import pandas as pd

# Rutas a los archivos CSV
archivo_business = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Business3.csv'
archivo_review = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/ReviewYelpConcat.csv'

# Cargar ambos archivos CSV en DataFrames
df_business = pd.read_csv(archivo_business)
df_review = pd.read_csv(archivo_review)

# Realizar la concatenación usando la columna "business_id"
df_resultado = pd.merge(df_review, df_business, on='business_id', how='inner')

# Guardar el resultado en un nuevo archivo CSV
df_resultado.to_csv('YelpReviewyBusiness.csv', index=False)

# Mostrar el DataFrame resultante con display
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
display(df_resultado)

,review_id,user_id,business_id,stars_x,useful,funny,cool,text,date,name,address,city,state,stars_y,review_count,attributes,categories,hours
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,2,0,0,0,This is the second time we tried turning point...,2017-05-13 17:06:55,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,4,2,0,1,The place is cute and the staff was very frien...,2017-08-08 00:58:18,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,We came on a Saturday morning after waiting a ...,2017-11-19 02:20:23,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
4,M0wzFFb7pefOPcxeRVbLag,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,2,0,0,0,"Mediocre at best. The decor is very nice, and ...",2017-09-09 17:49:47,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265989,BGSe6tne3hZXyB_DRf-tBg,ObZnTiwMA-4gaTqa1_mB6A,wsPBZXcq28mUE9B-CkdY8Q,2,1,0,0,This bar is definitely geared for its shriner ...,2022-01-08 22:05:04,El Korah Oasis,1118 W Idaho St,Boise,TN,4.5,7,"{'GoodForDancing': 'False', 'NoiseLevel': ""'qu...","Nightlife, Dive Bars, Arts & Entertainment, Ba...",NaN
4265990,REZ0pf6mAphzyolfTgfXKQ,YKVydQ6nZ3CsvSko8X8qTA,0vksR9cowkTN_xL-sdZnNw,1,0,0,0,The Restaurant at the Cheshire is average at b...,2021-12-31 14:48:32,The Restaurant at The Cheshire,7036 Clayton Ave,Saint Louis,TN,4.0,80,"{'NoiseLevel': ""u'average'"", 'RestaurantsDeliv...","Restaurants, American (New), British",NaN
4265991,YqkQOAxnG7jYs9m68Pm2FQ,VzuYiWOWg7RxJ9kEGw6ecA,LJkF_qtlpmTDZXMmjUr7xw,5,0,0,0,Very attentive and checked in via text wheneve...,2022-01-09 20:14:02,Food Lion,11459 Old Nashville Hwy,Smyrna,IN,5.0,5,"{'BikeParking': 'False', 'BusinessAcceptsCredi...","Grocery, Food","{'Monday': '6:0-23:0', 'Tuesday': '6:0-23:0', ..."
4265992,pPqcyyKyg3AruEOuhUPAJw,BIZt3IwVH66S0_UbMEh2MA,HaSEQCVzuVuMtJD_vVlfVg,1,2,2,0,Walked into this gas station and walked right ...,2021-01-02 00:54:42,Circle K,4802 N Sabino Canyon Rd,Tucson,FL,3.5,7,"{'BusinessParking': ""{'garage': False, 'street...","Food, Gas Stations, Automotive, Grocery, Conve...",NaN
4265993,Pi4sofBVDX_1FkiKG5ft5g,zQSW0_fi46U_066lo88GXQ,ujsFpiiGu92nUsjlFc9pew,1,0,0,0,I only come to this location because the parki...,2020-01-15 15:06:30,Quest Diagnostics,"4190 City Ave, Ste 416",Philadelphia,NV,1.0,5,{'ByAppointmentOnly': 'False'},"Health & Medical, Diagnostic Services, Medical...","{'Monday': '13:0-15:0', 'Tuesday': '13:0-15:0'..."

In [9]:
import pandas as pd

# Rutas a los archivos CSV
archivo_business = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/YelpReviewyBusiness.csv'

# Cargar el archivo CSV en un DataFrame
df_business = pd.read_csv(archivo_business)

# Acceder al valor en la columna 'text' de la primera fila (fila 0)
primer_texto = df_business['text'][0]

print(primer_texto)

If you decide to eat here, just be aware it is going to take about 2 hours from beginning to end. We have tried it multiple times, because I want to like it! I have been to it's other locations in NJ and never had a bad experience.

The food is good, but it takes a very long time to come out. The waitstaff is very young, but usually pleasant. We have just had too many experiences where we spent way too long waiting. We usually opt for another diner or restaurant on the weekends, in order to be done quicker.

In [10]:
import pandas as pd

archivo_csv = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/YelpReviewyBusiness.csv'

df = pd.read_csv(archivo_csv)

df.drop(columns=['stars_x', 'useful', 'funny', 'cool'], inplace=True)

# Guardar el DataFrame resultante en un nuevo archivo CSV
df.to_csv('YelpReviewyBusiness2.csv', index=False)

# Mostrar el DataFrame resultante con display
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
display(df),

,review_id,user_id,business_id,text,date,name,address,city,state,stars_y,review_count,attributes,categories,hours
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
1,VJxlBnJmCDIy8DFG0kjSow,Iaee7y6zdSB3B-kRCo4z1w,XQfwVwDr-v0ZS3_CbbE5Xw,This is the second time we tried turning point...,2017-05-13 17:06:55,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
2,S6pQZQocMB1WHMjTRbt77A,ejFxLGqQcWNLdNByJlIhnQ,XQfwVwDr-v0ZS3_CbbE5Xw,The place is cute and the staff was very frien...,2017-08-08 00:58:18,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
3,WqgTKVqWVHDHjnjEsBvUgg,f7xa0p_1V9lx53iIGN5Sug,XQfwVwDr-v0ZS3_CbbE5Xw,We came on a Saturday morning after waiting a ...,2017-11-19 02:20:23,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
4,M0wzFFb7pefOPcxeRVbLag,dCooFVCk8M1nVaQqcfTL3Q,XQfwVwDr-v0ZS3_CbbE5Xw,"Mediocre at best. The decor is very nice, and ...",2017-09-09 17:49:47,Turning Point of North Wales,1460 Bethlehem Pike,North Wales,PA,3.0,169,"{'NoiseLevel': ""u'average'"", 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...","{'Monday': '7:30-15:0', 'Tuesday': '7:30-15:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4265989,BGSe6tne3hZXyB_DRf-tBg,ObZnTiwMA-4gaTqa1_mB6A,wsPBZXcq28mUE9B-CkdY8Q,This bar is definitely geared for its shriner ...,2022-01-08 22:05:04,El Korah Oasis,1118 W Idaho St,Boise,TN,4.5,7,"{'GoodForDancing': 'False', 'NoiseLevel': ""'qu...","Nightlife, Dive Bars, Arts & Entertainment, Ba...",NaN
4265990,REZ0pf6mAphzyolfTgfXKQ,YKVydQ6nZ3CsvSko8X8qTA,0vksR9cowkTN_xL-sdZnNw,The Restaurant at the Cheshire is average at b...,2021-12-31 14:48:32,The Restaurant at The Cheshire,7036 Clayton Ave,Saint Louis,TN,4.0,80,"{'NoiseLevel': ""u'average'"", 'RestaurantsDeliv...","Restaurants, American (New), British",NaN
4265991,YqkQOAxnG7jYs9m68Pm2FQ,VzuYiWOWg7RxJ9kEGw6ecA,LJkF_qtlpmTDZXMmjUr7xw,Very attentive and checked in via text wheneve...,2022-01-09 20:14:02,Food Lion,11459 Old Nashville Hwy,Smyrna,IN,5.0,5,"{'BikeParking': 'False', 'BusinessAcceptsCredi...","Grocery, Food","{'Monday': '6:0-23:0', 'Tuesday': '6:0-23:0', ..."
4265992,pPqcyyKyg3AruEOuhUPAJw,BIZt3IwVH66S0_UbMEh2MA,HaSEQCVzuVuMtJD_vVlfVg,Walked into this gas station and walked right ...,2021-01-02 00:54:42,Circle K,4802 N Sabino Canyon Rd,Tucson,FL,3.5,7,"{'BusinessParking': ""{'garage': False, 'street...","Food, Gas Stations, Automotive, Grocery, Conve...",NaN
4265993,Pi4sofBVDX_1FkiKG5ft5g,zQSW0_fi46U_066lo88GXQ,ujsFpiiGu92nUsjlFc9pew,I only come to this location because the parki...,2020-01-15 15:06:30,Quest Diagnostics,"4190 City Ave, Ste 416",Philadelphia,NV,1.0,5,{'ByAppointmentOnly': 'False'},"Health & Medical, Diagnostic Services, Medical...","{'Monday': '13:0-15:0', 'Tuesday': '13:0-15:0'..."

In [2]:
import pandas as pd

# Ruta del archivo JSON
archivo_json = "C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Tip.csv"

# Leer el archivo JSON en un DataFrame de pandas
df = pd.read_json(archivo_json, lines=True)

# Especificar el nombre del archivo CSV de salida
archivo_csv = "Tip.csv"

# Guardar el DataFrame como un archivo CSV
df.to_csv(archivo_csv, index=False)

# Mostrar el contenido del DataFrame utilizando display
display(df)

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
...,...,...,...,...,...
908910,eYodOTF8pkqKPzHkcxZs-Q,3lHTewuKFt5IImbXJoFeDQ,Disappointed in one of your managers.,2021-09-11 19:18:57,0
908911,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,Great food and service.,2021-10-30 11:54:36,0
908912,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,Love their Cubans!!,2021-11-05 13:18:56,0
908913,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,Great pizza great price,2021-11-20 16:11:44,0
908914,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,Food is good value but a bit hot!,2021-12-07 22:30:00,0

In [3]:
import pandas as pd

# Ruta al archivo CSV
archivo_csv = "C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Tip.csv"

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv(archivo_csv)

# Calcular el porcentaje de nulos en cada columna
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100

# Mostrar el resultado
print(porcentaje_nulos)

user_id             0.00000
business_id         0.00000
text                0.00055
date                0.00000
compliment_count    0.00000
dtype: float64

In [4]:
import pandas as pd

# Ruta del archivo CSV
archivo_csv = "C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Tip.csv"

# Leer el archivo CSV en un DataFrame de pandas
df = pd.read_csv(archivo_csv)

# Cambiar el nombre de las columnas
df.rename(columns={'user_id': 'idUser', 'text': 'textTip', 'date': 'dateTip'}, inplace=True)

# Guardar el DataFrame con los nombres de columna modificados en el mismo archivo CSV
df.to_csv(archivo_csv, index=False)

# Mostrar el DataFrame con los nombres de columna modificados
display(df)

,idUser,business_id,textTip,dateTip,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
...,...,...,...,...,...
908910,eYodOTF8pkqKPzHkcxZs-Q,3lHTewuKFt5IImbXJoFeDQ,Disappointed in one of your managers.,2021-09-11 19:18:57,0
908911,1uxtQAuJ2T5Xwa_wp7kUnA,OaGf0Dp56ARhQwIDT90w_g,Great food and service.,2021-10-30 11:54:36,0
908912,v48Spe6WEpqehsF2xQADpg,hYnMeAO77RGyTtIzUSKYzQ,Love their Cubans!!,2021-11-05 13:18:56,0
908913,ckqKGM2hl7I9Chp5IpAhkw,s2eyoTuJrcP7I_XyjdhUHQ,Great pizza great price,2021-11-20 16:11:44,0
908914,4tF1CWdMxvvwpUIgGsDygA,_cb1Vg1NIWry8UA0jyuXnQ,Food is good value but a bit hot!,2021-12-07 22:30:00,0

In [6]:
import pandas as pd

# Ruta del archivo CSV
archivo_csv = "C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Tip.csv"

# Leer el archivo CSV en un DataFrame de pandas
df = pd.read_csv(archivo_csv)

# Mostrar el contenido del DataFrame utilizando display
display(df)

,idUser,business_id,textTip,dateTip,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,FjMQVZjSqY8syIO-53KFKw,hV-bABTK-glh5wj31ps_Jw,Very decent fried chicken,2017-06-27 23:05:38,0
4,ld0AperBXk1h6UbqmM80zw,_uN0OudeJ3Zl_tf6nxg5ww,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
...,...,...,...,...,...
338766,D9GvEwGme8fNP4wXyIvcvg,fX57gus0k0WY92W8r-Mlwg,Congratulations on the new spot James,2020-01-23 20:24:46,0
338767,-fbq-avXty6ua-N-8NSpJw,w58jPg7IMrWIfgtp1aO3Lg,Send in pictures of the damage to your vehicle...,2018-04-12 22:41:23,0
338768,E8ZPjNX63kfAuUL-U3s5Gg,2pLIQ0RHSmUbF0eIRT0LYg,Happy hour 4-6,2019-07-18 20:45:10,0
338769,ADohMwMk4a6oe_AYvSIY9g,AzseSGgDC6bVtMPEYo1CNQ,Raspberry sorbet is great. One scoop is plenty.,2013-07-13 18:03:57,0
338770,P4oGqCkYJ6a_LRheCUVUaA,_C7QiQQc47AOEv4PE3Kong,Lunch 25 cent martinis!,2012-01-16 18:18:14,0

In [ ]:
##No correr

import pandas as pd

# Rutas a los archivos CSV
archivo_Tip = "C:/Users/Fede/Documents/Henry/Proyecto 3/etl/Tip.csv"
archivo_business = 'C:/Users/Fede/Documents/Henry/Proyecto 3/etl/YelpReviewyBusiness2.csv'

# Cargar ambos archivos CSV en DataFrames
df_business = pd.read_csv(archivo_business)
archivo_Tip = pd.read_csv(archivo_Tip)

# Realizar la concatenación usando la columna "business_id"
df_resultado = pd.merge(archivo_Tip, df_business, on='business_id', how='inner')

# Guardar el resultado en un nuevo archivo CSV
df_resultado.to_csv('YelpCompleto.csv', index=False)

# Mostrar el DataFrame resultante con display
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
display(df_resultado)